apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
  namespace: ci-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
        - name: python-backend
          image: registry.minikube/python-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
